### ISSUE TITLE
Giant TODO

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/CytofDensityEstimation#2]
- [x] Write Simulation Studies
    - Set K in MCMC = 5. Find beta estimate and `F_i` estimate
    - [x] Case 1: beta=1. gammaC=0.3, gammaT=0.2, etaC=(.5,.5,0), etaT=(.5, .2, .3)
    - [x] Case 2: beta=1. gammaC=gammaT=0.3. etaC=(.5, .5, 0), etaT=(.5, .2, .3)
    - [x] Case 3: beta=0. gammaC=gammaT=0.3. etaC=(.5, .5, 0), etaT=(.5, .5, 0)
- [x] Type joint posterior in paper sketch
- [x] Change implementation of `gibbs`
    - [x] `nmcmc` -> `nsamps::Vector{Int}`, `thins` -> `thin::Int`
        - desired behavior: provide `nsamps::Vector{Int}` which needs to be 
          in descending order. `nsamps` needs to be same length as `monitors`.
          `thin` specifies how the first monitor should be thinned. So, if
          `nsamps=[1000, 10], thin=2, burn=20`, then total number number
          iterations is `burn + nsamps[1] * thin = 10 + 1000 * 2 = 2020`.
          After the burn-in period, thin accordingly for the second monitor so
          that in the end, 10 samples are collected.'
- [x] Implement `fit`
    - No need to keep `v` and `zeta` as the original `SkewT` parameters can be
      recovered from `psi` and `omega`.
- [x] Simulate data
- [x] Methods for plotting data
- [x] Compare results to KS using `HypothesisTests.ApproximateTwoSampleKSTest`
- [x] Methods for post processing
    - [x] Test that `plots.gr()` works on server
    - [x] Plot makers for each parameter
    - [x] Credible interval for density estimate
