### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/CytofDensityEstimation#4]
- [x] Implement ordered mu.
- [x] Focus on finding out why P(beta=1 | data) is close to 1 even when the posterior estimates of G_i and r_i are not different under the conditions.   We may end up throwing \beta away.  In such a case, we let \eta and \gamma indexed by i and compare estimates. But before making that step, it is good to check why the conclusion based on the posterior mean of beta does not agree with visual inspection of the posterior estimates of G_i and r_i.   As discussed during the meeting, it is likely that a difference is there but we just don't see them from the graph for CD56 and Granzyme A. To find that out, we may check the followings;
    - [x] Under the two different values of \beta, what are the distributions of the parameters in the log-skew-t distributions?  Are they different?  2. What about eta_i when \beta=1?  Are \eta_T and \eta_C different enough to conclude that the two distributions are different?   
    - [ ] Let's see what we find for CD56 and Grazyme A etc.  Later, if needed, we can use metrics comparing two probability distributions, e.g., total variation distance.  This won't be a problem.

***

- [x] Describe how I got images in Figure 5. Emphasize that the left figures are the posterior estimates of `G_i`, and the figures on the right are the marginal posterior distributions of the `gamma_i`.
- [x] Use new DIC plot (from CDD.jl)
- [x] Markers, CD56 and GranzymeA look very similar for the two samples, so we may need to find why/how they are different and why/how difference is big enough to conclude they are differentially distributed. 
  - [x] For GranzymeA, there are few 0's. So the difference is due mostly to the G_i's. It may be sample-size related. The Bayes Factor is 19.03. I think if the sample size were smaller, the Bayes factor would also be smaller. 
  - [x] For LAG3, more than half of the data are 0's in both samples. So the difference in the F_i's might be due to the difference in the gamma_i's. What I can do for this one is perhaps compute the Bayes factor without the including gamma_i's.
- [ ] Sensitivity to K for simulation and data analysis
- [ ] Get posterior predictives of y for C and T. Calculate probability that `P(y_{i, future} < c | data)` from posterior predictive samples. (FUTURE WORK)

**Comment by luiarthur** [comment]
![image](https://user-images.githubusercontent.com/5297817/101319822-73045880-3817-11eb-91e7-b7cf5d665cdc.png)
